pipeline:
  build:
    image: alpine
    commands:
      - apk --no-cache add python3 py3-pip python3-dev
      - pip install -r requirements.txt
      - pip install -r tests/requirements.txt
      - pip install .
      - pytest -v

  slack:
    image: plugins/slack
    channel: tools
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      event: push
